-- AlterTable
ALTER TABLE "Posts" ALTER COLUMN "DateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "Like" DROP NOT NULL,
ALTER COLUMN "DisLike" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Replies" ADD COLUMN     "DateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "Like" DROP NOT NULL,
ALTER COLUMN "DisLike" DROP NOT NULL;
